### ISSUE TITLE
Minitest support?

### ISSUE THREAD

**Issue by cmckni3** [elabs/christmas_tree_formatter#8]
I think it would be neat if it supported minitest as well.

**Comment by Burgestrand** [comment]
Indeed! I don't really use minitest, so a pull request for it would be much appreciated!

**Comment by cmckni3** [comment]
Awesome. I'll see if I have time to work on it.

**Comment by cmckni3** [comment]
Almost done adding minitest support. Fixing the summary and I'll send a PR.

**Comment by cmckni3** [comment]
Added in #10
